### ISSUE TITLE
Interesting..

### ISSUE THREAD

**Issue by devinrhode2** [justinwoo/ember-cli-api-stub-static#1]
I've been trying to figure out a way to use a static folder of pre-canned json api responses essentially as a spec for an application - something that can be used to test 

I've been searching for something that can be used to serve ember pre-canned json for GET _and_ POST requests, and preferably that thing also has a server mode that can fire requests to the live backend and validate they match what's expected in the folder of pre-canned json.

So there would be this `testjson` folder, essentially providing front and back end teams a spec for what the json api should be. Here's my current idea for what that folder would look like:

```
testjson/
  /todo
    /0 -> a file with no extension and just an example json response
    /1 -> another json object for another todo
  /todos -> another json file, an array consisting of todos 0 and 1
  /todos/new -> responds to POST request with a new todo (doesn't necessarily have to have ID 2)
```

Essentially it's just a different take on fixture data - the idea is you would just keep it in it's own folder and it _can_ be used for unit testing of the client and server side. I'm not sure it would lend itself very well to integration testing. I feel like something for testing API's already exists in some form.

**Comment by devinrhode2** [comment]
So I have to ask: along with setting pre-canned json for GET responses, how could POST responses be handled?

**Comment by justinwoo** [comment]
Just a quick response, I think most Ember folks (especially those using Ember Data) won't like your API using `POST /todos/new` to create a resource. [see here](http://emberjs.com/guides/models/the-rest-adapter/)

That said, I think it might be better to have a more complex object instead of the simple response bodies that I originally implemented so that GET/POST/PUT/etc. requests can be handled accordingly.

Give me a day or two (or ping me again) and I'll try to go over what you wrote and suggest some ideas (I'm "busy" playing video games at the moment).

**Comment by justinwoo** [comment]
Here's the bit I was talking about with the simple response bodies: https://github.com/kimagure/ember-cli-api-stub-static/blob/master/blueprints/api-stub-static/files/server/index.js#L14

Since right now I just read the file and spit it back to out the client, maybe it'd be better to do some extra duty to parse the JSON and return the "get" property of it to GET requests, "post" property to POST requests, etc.

**Comment by justinwoo** [comment]
Hi @devinrhode2, have you given any thought to any improvements here? Have you been using this module, or have you found other solutions to be more helpful?

**Comment by devinrhode2** [comment]
Well, ember-cli uses EmberJS, if you search ember-cli.com for "Express"
you'll see what I'm talking about, and if you search ember-cli/issues for
"testjson" "devinrhode2" then you should see my comment about putting
testjson in it's own folder instead of in model files (how ember cli
currently does it)

-Devin http://zerply.com/DevinRhode2
http://zerply.com/devinrhode2

**Comment by devinrhode2** [comment]
Link to the issue I was talking about:
https://github.com/stefanpenner/ember-cli/issues/153#issuecomment-63218842
I mean ember-cli users _ExpressJS_

-Devin http://zerply.com/DevinRhode2
http://zerply.com/devinrhode2
